import {
  BookOpenText,
  CalendarDays,
  CalendarRange,
  ChartNoAxesColumnIncreasing,
  ClipboardCheck,
  FileText,
  FolderKanban,
  GraduationCap,
  LayoutDashboard,
  MessageCircleMore,
  PackageSearch,
  Settings,
  Users,
  Video,
} from "lucide-react";

export const dashboardNavigation = [
  { href: "/dashboard", label: "Beranda", icon: LayoutDashboard },
  { href: "/record", label: "Catat Kelas", icon: ClipboardCheck },
  { href: "/classes", label: "Kelas", icon: GraduationCap },
  { href: "/students", label: "Murid", icon: Users },
  { href: "/assessment", label: "Penilaian", icon: ChartNoAxesColumnIncreasing },
  { href: "/journal", label: "Jurnal", icon: BookOpenText },
  { href: "/documents", label: "Dokumen", icon: FileText },
  { href: "/events", label: "Acara", icon: CalendarRange },
  { href: "/meetings", label: "Rapat", icon: Video },
  { href: "/operations", label: "Operasional", icon: PackageSearch },
  { href: "/portfolios", label: "Portofolio", icon: FolderKanban },
  { href: "/connect", label: "Connect", icon: MessageCircleMore },
  { href: "/schedule", label: "Jadwal", icon: CalendarDays },
  { href: "/settings", label: "Pengaturan", icon: Settings },
] as const;
