import {
  Award,
  BookOpen,
  CalendarDays,
  FileCheck2,
  FileText,
  FileSpreadsheet,
  GraduationCap,
  LayoutDashboard,
  ListTodo,
  Settings,
  Users,
  Presentation,
  Megaphone,
  BriefcaseBusiness,
  Archive,
} from "lucide-react";

export const dashboardNavigation = [
  { href: "/dashboard", label: "Beranda", icon: LayoutDashboard },
  { href: "/classes", label: "Kelas", icon: GraduationCap },
  { href: "/attendance", label: "Presensi", icon: FileCheck2 },
  { href: "/journal", label: "Jurnal", icon: BookOpen },
  { href: "/students", label: "Murid", icon: Users },
  { href: "/record", label: "Catat Kelas", icon: FileCheck2 },
  { href: "/assessment", label: "Penilaian", icon: FileSpreadsheet },
  { href: "/grades", label: "Buku Nilai", icon: Award },
  { href: "/recap", label: "Rekap & Tindak Lanjut", icon: ListTodo },
  { href: "/schedules", label: "Jadwal", icon: CalendarDays },
  { href: "/documents", label: "Dokumen & Surat", icon: FileText },
  { href: "/events", label: "Acara", icon: Presentation },
  { href: "/meetings", label: "Rapat & Keputusan", icon: Users },
  { href: "/operations/inventory", label: "Inventaris", icon: Archive },
  { href: "/operations/maintenance", label: "Lapor Kerusakan", icon: Settings },
  { href: "/operations/duty", label: "Jadwal Piket", icon: CalendarDays },
  { href: "/portfolios", label: "Portofolio", icon: BriefcaseBusiness },
  { href: "/connect", label: "Komunikasi", icon: Megaphone },
  { href: "/settings", label: "Pengaturan", icon: Settings },
] as const;
